apiVersion: v1
kind: Pod
metadata:
  name: kyo
  labels:
    app: kyo
spec:
  containers:
    - name: np-container
      image: kyontoki/ng:62
---
apiVersion: v1
kind: Service
metadata:
  name: kyo-svc
spec:
  selector:
    app: kyo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
